# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.2.1" # for syncing
wally = "upliftgames/wally@0.3.1" # for package management
selene = "kampfkarren/selene@0.23.1" # for static linting
stylua = "JohnnyMorganz/stylua@0.15.3" # for styling
luau-lsp = "JohnnyMorganz/luau-lsp@1.14.3" # for LSP
lune = "filiptibell/lune@0.4.0"
