[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Multi-paradigm"
description = "Vinum offers state centralization and self-containment in a single interface, which allows for the maximum integration between the two."

[[home.features]]
title = "Blazingly Fast"
description = "Vinum is insanely optimized to yield incredible speed. Becuase of this, Vinum is the best of its kind for performance-critical systems."

[[home.features]]
title = "Strict and Flexible"
description = "Vinum is a balance of strictness and flexibility. Some limitations are present to solve greater issues, and some features are 'minimal' in nature to support flexibility."

[[home.features]]
title = "Declarative API"
description = "State management is dead simple- no need to manually manage dependencies!"

[[navbar.items]]
href = "/Vinum/Contributing"
label = "Contributing"
position = "left"

[footer]
style = "dark"
copyright = "Copyright © 2022 Sinlerdev. Built with Moonwave and Docusaurus"