[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Multi-paradigm"
description = "Vinum doesn't 'force' you into either centralized or self-contained paradigms, in fact, it allows for powerful integration between the two to leverage the best of the two worlds."

[[home.features]]
title = "Blazingly Fast"
description = "Vinum is insanely optimized to yield benchmark results that don't exceed 1.3us, in fact, most of the results were lower than a microsecond. Due to this incredible speed, Vinum is the best of its kind for performance critical systems."

[[home.features]]
title = "Strict and Flexible"
description = "In Vinum, you have to pass a processor function that allows for you to manage middleware, garbage collection, and even typechecking - although you aren't allowed to alter outcome as this decreases predictability."

[[home.features]]
title = "Declarative API"
description = "State management in Vinum is beautifully simple and scalable - no boilerplate code for implementing a simple feature!"

[[home.features]]
title = "No Dependencies"
description = "In Vinum, you don't have to worry about dependency management and optimization, all of that is abstracted away and heavily optimized by Vinum."

[[navbar.items]]
href = "/Vinum/Contributing"
label = "Contributing"
position = "left"

[footer]
style = "dark"
copyright = "Copyright © 2022 Sinlerdev. Built with Moonwave and Docusaurus"