[package]
name = "plothan/vinum"
version = "0.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A declarative library focusing on making relations between data easy."

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]
[dependencies]